version: 2.1
jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest

  deploy:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: |
            # Add your deployment steps here
      - run:
          name: Start SSH agent
          command: eval $(ssh-agent -s)
      - run:
          name: Add SSH key to agent
          command: ssh-add /root/.ssh/id_rsa

